### ISSUE TITLE
install.py: error: the following arguments are required: path

### ISSUE THREAD

**Issue by rbrtmrtn** [internet-equity/netrics#50]
## 🐞 Bug Report:

Hello and thank you for this awesome project! 👋 I'm trying to install Netrics on a RasPi 4B using the one-liner, and running into an error.

### Current Behavior:

When I run the one-liner:

```bash
curl -sL https://github.com/internet-equity/netrics/raw/0.0.1-rc.18/install.py | python3
```

I get an error:

```bash
usage: install.py [-h] [-f] [-U] [--pre] path
install.py: error: the following arguments are required: path
```

### Expected Behavior:

I expect it to install.

### Steps to Reproduce:

[I think I covered this above, but please let me know if any other details would be helpful]

### Screenshots/Code Snippets:

n/a

### Environment:

RasPi 4B; results of `lsb_release -a`:

```bash
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

### Additional Information:

n/a

**Comment by marcwitasee** [comment]
Hi @rbrtmrtn, thanks so much for filling out our issue form! Seems like you are having issues with the installation script. Can you try running the same command on your device with an extra flag as such:

```
curl -sL https://github.com/internet-equity/netrics/raw/0.0.1-rc.18/install.py | sudo python3 - --pre --upgrade
```
Let me know if you are able successfully install with this line.

**Comment by rbrtmrtn** [comment]
Hi @marcwitasee , thanks for following up about this! I ran that command and it worked.

**Comment by jesteria** [comment]
Looks like everything was figured out here! Just for posterity:

* At issue is that the installer couldn't find a suitable location for the pre-built executables on its own. It was presumably invoked by a non-root user, who _couldn't_ write to `/usr/local/bin/` (its preference), and who had neither alternate directory on their `PATH`: `~/.local/bin/` & `~/bin/`. Rather than write to a location which wouldn't work, the installer required specification of a path. I don't think that this is unreasonable; however, it could perhaps be better documented. I've added a note about this to the readme.
* The above was resolved by the direction to invoke the installer with `sudo` (as the root user). This makes sense for a typical installation, and the root user _was able_ to write to `/usr/local/bin/` (presumably).
* The direction to use the `--pre` argument was in fact _also_ necessary – so long as Netrics is in beta. A note about this has also been added to the readme.

Cheers :slightly_smiling_face:
